{% set name = "lakepy" %}
{% set version = "3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lakepy-{{ version }}.tar.gz
  sha256: 9d34fe09f4f15887dcefe265c472cc232855d7fde5ce3c930c99d6c98570bb06

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - contextily
    - geopandas
    - ipython
    - leafmap
    - matplotlib-base
    - more-itertools ==8.4
    - numpy
    - pandas
    - plotly
    - pymysql
    - seaborn
    - shapely
    - tabulate

test:
  imports:
    - lakepy
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/ESIPFed/LakePy
  summary: Provides access to the Global Lake Level Database and extended functionality for lake water level analysis
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - xeulha
